//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scenes/AirPlane/Act.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scenes/AirPlane/Act.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Act: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Act()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Act"",
    ""maps"": [
        {
            ""name"": ""Jet"",
            ""id"": ""31ef6840-6413-4dee-a012-cc5d7ea17de9"",
            ""actions"": [
                {
                    ""name"": ""ThrottleUp"",
                    ""type"": ""Button"",
                    ""id"": ""4135512d-5e14-4898-b4fd-66bcf7865681"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleDown"",
                    ""type"": ""Button"",
                    ""id"": ""e32cee64-abb1-4584-9efa-6bd6717fce5a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleStepUp"",
                    ""type"": ""Button"",
                    ""id"": ""98535cb5-0fa9-4440-8c05-375cd6b35127"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleStepDown"",
                    ""type"": ""Button"",
                    ""id"": ""9b347419-aad9-45db-9c70-eb10dadb9b4f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleAB"",
                    ""type"": ""Button"",
                    ""id"": ""7e83b190-df0f-44a4-9c9f-22998e45bedf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""184a7edb-d082-47df-b1ca-4b84c84dd892"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c31eb9ae-c4ac-4198-b4cc-8a49883a7c5e"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58c35a83-bd8b-48e4-820a-e2551beb5879"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleStepUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""937ee96c-85cf-4cdf-a135-55173e8af43c"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleStepDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""508d115a-11a6-4e2f-a7eb-bc55c67b9ab0"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jet
        m_Jet = asset.FindActionMap("Jet", throwIfNotFound: true);
        m_Jet_ThrottleUp = m_Jet.FindAction("ThrottleUp", throwIfNotFound: true);
        m_Jet_ThrottleDown = m_Jet.FindAction("ThrottleDown", throwIfNotFound: true);
        m_Jet_ThrottleStepUp = m_Jet.FindAction("ThrottleStepUp", throwIfNotFound: true);
        m_Jet_ThrottleStepDown = m_Jet.FindAction("ThrottleStepDown", throwIfNotFound: true);
        m_Jet_ToggleAB = m_Jet.FindAction("ToggleAB", throwIfNotFound: true);
    }

    ~@Act()
    {
        UnityEngine.Debug.Assert(!m_Jet.enabled, "This will cause a leak and performance issues, Act.Jet.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jet
    private readonly InputActionMap m_Jet;
    private List<IJetActions> m_JetActionsCallbackInterfaces = new List<IJetActions>();
    private readonly InputAction m_Jet_ThrottleUp;
    private readonly InputAction m_Jet_ThrottleDown;
    private readonly InputAction m_Jet_ThrottleStepUp;
    private readonly InputAction m_Jet_ThrottleStepDown;
    private readonly InputAction m_Jet_ToggleAB;
    /// <summary>
    /// Provides access to input actions defined in input action map "Jet".
    /// </summary>
    public struct JetActions
    {
        private @Act m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public JetActions(@Act wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Jet/ThrottleUp".
        /// </summary>
        public InputAction @ThrottleUp => m_Wrapper.m_Jet_ThrottleUp;
        /// <summary>
        /// Provides access to the underlying input action "Jet/ThrottleDown".
        /// </summary>
        public InputAction @ThrottleDown => m_Wrapper.m_Jet_ThrottleDown;
        /// <summary>
        /// Provides access to the underlying input action "Jet/ThrottleStepUp".
        /// </summary>
        public InputAction @ThrottleStepUp => m_Wrapper.m_Jet_ThrottleStepUp;
        /// <summary>
        /// Provides access to the underlying input action "Jet/ThrottleStepDown".
        /// </summary>
        public InputAction @ThrottleStepDown => m_Wrapper.m_Jet_ThrottleStepDown;
        /// <summary>
        /// Provides access to the underlying input action "Jet/ToggleAB".
        /// </summary>
        public InputAction @ToggleAB => m_Wrapper.m_Jet_ToggleAB;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Jet; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="JetActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(JetActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="JetActions" />
        public void AddCallbacks(IJetActions instance)
        {
            if (instance == null || m_Wrapper.m_JetActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JetActionsCallbackInterfaces.Add(instance);
            @ThrottleUp.started += instance.OnThrottleUp;
            @ThrottleUp.performed += instance.OnThrottleUp;
            @ThrottleUp.canceled += instance.OnThrottleUp;
            @ThrottleDown.started += instance.OnThrottleDown;
            @ThrottleDown.performed += instance.OnThrottleDown;
            @ThrottleDown.canceled += instance.OnThrottleDown;
            @ThrottleStepUp.started += instance.OnThrottleStepUp;
            @ThrottleStepUp.performed += instance.OnThrottleStepUp;
            @ThrottleStepUp.canceled += instance.OnThrottleStepUp;
            @ThrottleStepDown.started += instance.OnThrottleStepDown;
            @ThrottleStepDown.performed += instance.OnThrottleStepDown;
            @ThrottleStepDown.canceled += instance.OnThrottleStepDown;
            @ToggleAB.started += instance.OnToggleAB;
            @ToggleAB.performed += instance.OnToggleAB;
            @ToggleAB.canceled += instance.OnToggleAB;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="JetActions" />
        private void UnregisterCallbacks(IJetActions instance)
        {
            @ThrottleUp.started -= instance.OnThrottleUp;
            @ThrottleUp.performed -= instance.OnThrottleUp;
            @ThrottleUp.canceled -= instance.OnThrottleUp;
            @ThrottleDown.started -= instance.OnThrottleDown;
            @ThrottleDown.performed -= instance.OnThrottleDown;
            @ThrottleDown.canceled -= instance.OnThrottleDown;
            @ThrottleStepUp.started -= instance.OnThrottleStepUp;
            @ThrottleStepUp.performed -= instance.OnThrottleStepUp;
            @ThrottleStepUp.canceled -= instance.OnThrottleStepUp;
            @ThrottleStepDown.started -= instance.OnThrottleStepDown;
            @ThrottleStepDown.performed -= instance.OnThrottleStepDown;
            @ThrottleStepDown.canceled -= instance.OnThrottleStepDown;
            @ToggleAB.started -= instance.OnToggleAB;
            @ToggleAB.performed -= instance.OnToggleAB;
            @ToggleAB.canceled -= instance.OnToggleAB;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="JetActions.UnregisterCallbacks(IJetActions)" />.
        /// </summary>
        /// <seealso cref="JetActions.UnregisterCallbacks(IJetActions)" />
        public void RemoveCallbacks(IJetActions instance)
        {
            if (m_Wrapper.m_JetActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="JetActions.AddCallbacks(IJetActions)" />
        /// <seealso cref="JetActions.RemoveCallbacks(IJetActions)" />
        /// <seealso cref="JetActions.UnregisterCallbacks(IJetActions)" />
        public void SetCallbacks(IJetActions instance)
        {
            foreach (var item in m_Wrapper.m_JetActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JetActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="JetActions" /> instance referencing this action map.
    /// </summary>
    public JetActions @Jet => new JetActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Jet" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="JetActions.AddCallbacks(IJetActions)" />
    /// <seealso cref="JetActions.RemoveCallbacks(IJetActions)" />
    public interface IJetActions
    {
        /// <summary>
        /// Method invoked when associated input action "ThrottleUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrottleDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrottleStepUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleStepUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrottleStepDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleStepDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleAB" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleAB(InputAction.CallbackContext context);
    }
}
